#
#
#

include Makefile.inc

root_dir	= ..

all: $(root_dir)/README.md search-option.md

clean:
	rm -f README.md

$(root_dir)/README.md: ./README.md
	cp $< $@

README.md: README.md4

search-option.md: search-option.md4


